#!/usr/bin/env python3
"""Fetch each discovery candidate's body, so the intake agent never has to.

The intake prompt used to hand the agent a curl command and three `--show`
invocations and ask it to fetch one body per candidate. That made the agent a
network client, which is the one thing an injected agent most wants to be: the
same command that fetches a Reddit thread will happily fetch an attacker's
collector with the interesting parts of this repository in the query string.

The review agent has never had that problem, because render_review_packets.py
puts the evidence in the prompt before the agent starts. This is the same
pattern for intake. The driver runs it as the operator account, before
dropping privilege; the agent receives text and no reason to reach the
network at all.

Every body is untrusted, so every body is fenced with a per-run nonce that the
trusted part of the prompt names. The nonce is not a security boundary by
itself, and it is not claimed as one: it is there so that content which
imitates the prompt's own structure cannot silently become part of it. Any
occurrence of the marker inside a body is neutralised before fencing, which is
the part that actually matters.

One request per candidate, POLITE_DELAY apart, no crawling: the same volume
discipline the discovery scripts keep.

Usage:
    hydrate_candidates.py --nonce <hex> [--max-chars N] < candidate-lines
"""
from __future__ import annotations

import argparse
import os
import re
import subprocess
import sys
import time
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
PY = str(ROOT / ".venv/bin/python")
POLITE_DELAY = 1.5
# The X watcher's own spacing between profile reads, kept for post lookups so
# hydration cannot become the reason an account-health signal trips.
X_DELAY = 1.5
TIMEOUT = 240

# Platform, in the order the intake queue mixes them. Each entry is the
# pattern that recognises a candidate URL and the reader that fetches it.
PLATFORMS = (
    ("stackernews", re.compile(r"stacker\.news/items/(\d+)"),
     "discover_stackernews.py"),
    ("reddit", re.compile(r"reddit\.com/r/[^/]+/comments/([0-9a-z]+)"),
     "discover_reddit.py"),
    ("bitcointalk", re.compile(r"bitcointalk\.org/index\.php\?topic=(\d+)"),
     "discover_bitcointalk.py"),
    ("nostr", re.compile(r"njump\.me/(note1[023456789acdefghjklmnpqrstuvwxyz]+)"),
     "discover_nostr.py"),
)

# X candidates are a separate lane: a different agent, a different prompt, and
# an operator's explicit --include-x rather than the 12-hourly timer. The
# hydration is the same idea, and the gain is larger, because reading a post
# through the official API needs the bearer token. Pre-hydrating means the
# token stays in the driver and the agent never holds a credential at all.
X_PLATFORM = ("x", re.compile(r"x\.com/[^/]+/status/(\d+)"), "discover_x.py")


def classify(line: str, include_x: bool) -> tuple[str, str, str] | None:
    platforms = (*PLATFORMS, X_PLATFORM) if include_x else PLATFORMS
    for name, pattern, script in platforms:
        match = pattern.search(line)
        if match:
            return name, match.group(1), script
    return None


def fetch(script: str, ident: str) -> tuple[bool, str]:
    env = None
    if script == "discover_x.py":
        # The watcher fails closed unless told it may make a live read. The
        # driver has already decided that by passing --include-x.
        env = {**os.environ, "X_DISCOVERY_ENABLED": "true"}
    try:
        result = subprocess.run(
            [PY, str(ROOT / "scripts" / script), "--show", ident],
            cwd=ROOT, capture_output=True, text=True, timeout=TIMEOUT, env=env)
    except subprocess.TimeoutExpired:
        return False, f"timed out after {TIMEOUT}s"
    if result.returncode != 0:
        detail = (result.stderr or result.stdout).strip().splitlines()
        return False, (detail[-1] if detail else f"exit {result.returncode}")
    return True, result.stdout


PLACEHOLDER = re.compile(r"\{([A-Z][A-Z0-9_]{2,})\}")


def neutralise(text: str, nonce: str) -> str:
    """Stop a body from closing the fence it is inside, or filling a slot.

    A candidate body is text somebody else wrote, and the marker is printed
    in the prompt above it, so a body can contain the marker. Replacing it
    with a visibly mangled form keeps the fence unambiguous and keeps the
    tampering visible to a reader of the prompt. The same applies to anything
    shaped like one of render_agent_prompt.py's placeholders.
    """
    text = text.replace(nonce, f"{nonce[:4]}-REMOVED-BY-HYDRATION")
    return PLACEHOLDER.sub(lambda m: f"(placeholder {m.group(1)} removed)", text)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--nonce", required=True,
                        help="per-run fence marker, generated by the driver")
    parser.add_argument("--max-chars", type=int, default=8000,
                        help="per-candidate ceiling on hydrated text")
    parser.add_argument("--delay", type=float, default=POLITE_DELAY)
    parser.add_argument("--include-x", action="store_true",
                        help="also hydrate X permalinks, for an operator-"
                             "approved triage run")
    args = parser.parse_args()
    if args.include_x:
        args.delay = max(args.delay, X_DELAY)

    lines = [line.rstrip("\n") for line in sys.stdin if line.strip()]
    open_fence = f"<<<UNTRUSTED-{args.nonce}"
    close_fence = f"UNTRUSTED-{args.nonce}>>>"

    fetched = 0
    for index, line in enumerate(lines, 1):
        print(f"### Candidate {index}")
        print(f"Queue line: {neutralise(line, args.nonce)}")
        target = classify(line, args.include_x)
        if target is None:
            reason = ("an X permalink, triaged in its own lane"
                      if X_PLATFORM[1].search(line)
                      else "no recognised platform URL")
            print(f"Body: not hydrated ({reason})")
            print()
            continue
        platform, ident, script = target
        print(f"Platform: {platform} (id {ident})")
        if fetched:
            time.sleep(args.delay)
        ok, payload = fetch(script, ident)
        fetched += 1
        if not ok:
            print(f"Body: fetch failed ({payload})")
            print("Leave this candidate Pending and report the failure.")
            print()
            continue
        body = neutralise(payload, args.nonce)
        truncated = len(body) > args.max_chars
        if truncated:
            body = body[:args.max_chars]
        print(f"Body: hydrated, {'truncated' if truncated else 'complete'}")
        print(open_fence)
        print(body.rstrip())
        print(close_fence)
        print()

    print(f"Hydrated {fetched} of {len(lines)} candidate(s) with one request "
          f"each.", file=sys.stderr)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
